optipng.exe -o 7 ../ReferenceOutput/DetectEdgesTest/*.png
optipng.exe -o 7 ../ReferenceOutput/JpegDecoderTests/*.png
optipng.exe -o 7 ../ReferenceOutput/ResizeTests/*.png
optipng.exe -o 7 ../ReferenceOutput/TestImageExtensionsTests/*.png
optipng.exe -o 7 ../ReferenceOutput/AffineTransformTests/*.png
optipng.exe -o 7 ../ReferenceOutput/GifDecoderTests/**/*.png
optipng.exe -o 7 ../ReferenceOutput/PorterDuffCompositorTests/**/*.png
optipng.exe -o 7 ../ReferenceOutput/ProjectiveTransformTests/**/*.png
optipng.exe -o 7 ../ReferenceOutput/Drawing/GradientBrushes/**/*.png
optipng.exe -o 7 ../ReferenceOutput/Drawing/Text/**/*.png